name: Build Chromium

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Check disk space
        run: df -h

      - uses: actions/checkout@v4

      - name: Fetch depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Fetch Chromium source
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          mkdir chromium
          cd chromium
          fetch --nohooks --no-history chromium

      - name: Check disk space
        run: df -h

      - name: Install build deps
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          ./build/install-build-deps.sh

      - name: Check disk space
        run: df -h

      - name: gclient runhooks
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          gclient runhooks

      - name: Set build config
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          gn gen out/Default
          echo "enable_nacl=false" >> out/Default/args.gn
          echo "symbol_level=0" >> out/Default/args.gn
          echo "blink_symbol_level=0" >> out/Default/args.gn
          echo "is_debug=false" >> out/Default/args.gn
          echo "is_component_build=true" >> out/Default/args.gn
          gn gen out/Default

      - name: Build
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          autoninja -C out/Default chrome

      - uses: actions/upload-artifact@v2
        with:
          name: out/Default
          path: chromium/src/out/Default
